name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: add build folder
      run: mkdir build
    - name: move in build
      run: cd build
    - name: cmake 
      run: cmake ..
    - name: make
      run: make ..
