name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: mkdir build && mkdir 3rdparty && cd 3rdparty && git submodule add https://github.com/google/googletest && cd build && cmake .. && make -j
