name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: mkdir build && git submodule add https://github.com/google/googletest 3rdparty && cd build && cmake .. && make -j
    - name: test
      run: cd build/B && ../C/C && ../C/CTestExe 
